### ISSUE TITLE
git clone of repo fails

### ISSUE THREAD

**Issue by sgosline** [fraenkel-lab/OmicsIntegrator#32]
Filing this here, in case it's something with my configuration and/or location.

I'm trying to do a git clone of the repo from Europe. I have git v. 2.17.1 on mac OSx (mojave).
```
Downloading dist/OmicsIntegrator-0.3.1.tar.gz (562.57 MB)
Error accessing media: dist/OmicsIntegrator-0.3.1.tar.gz (56364cf3296bc88b5b21ac2c3fd0a46f48b063e7c4aa1adb4297ba7d1a3c5b13)
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xcc680]

goroutine 1 [running]:
runtime.throw(0x50c640, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc8202094a8 sp=0xc820209490
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8202094f8 sp=0xc8202094a8
sync.(*Pool).Get(0x6b2820, 0x0, 0x0)
	/usr/local/go/src/sync/pool.go:101 +0x40 fp=0xc820209548 sp=0xc8202094f8
fmt.newPrinter(0xc82006df70)
	/usr/local/go/src/fmt/print.go:133 +0x27 fp=0xc820209588 sp=0xc820209548
fmt.Fprintln(0xc641c0, 0xc820032018, 0xc820209718, 0x1, 0x1, 0x542979, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:253 +0x2d fp=0xc8202095d0 sp=0xc820209588
github.com/github/git-lfs/commands.logPanicToWriter(0xc641c0, 0xc820032018, 0x7ba2f0, 0xc82000e370)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:160 +0x1e9 fp=0xc820209868 sp=0xc8202095d0
github.com/github/git-lfs/commands.logPanic(0x7ba2f0, 0xc82000e370, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x421 fp=0xc8202099e8 sp=0xc820209868
github.com/github/git-lfs/commands.handlePanic(0x7ba2f0, 0xc82000e370, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e fp=0xc820209a10 sp=0xc8202099e8
github.com/github/git-lfs/commands.LoggedError(0x7ba2f0, 0xc82000e370, 0x4db960, 0x1e, 0xc820209d00, 0x2, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x82 fp=0xc820209ad8 sp=0xc820209a10
github.com/github/git-lfs/commands.smudgeCommand(0x6aeee0, 0xc82006d7e0, 0x1, 0x1)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:78 +0xd56 fp=0xc820209d48 sp=0xc820209ad8
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x6aeee0, 0xc82006d730, 0x1, 0x1, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403 fp=0xc820209e10 sp=0xc820209d48
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x6afbe0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a fp=0xc820209f18 sp=0xc820209e10
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:88 +0x23 fp=0xc820209f38 sp=0xc820209f18
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:9 +0x14 fp=0xc820209f40 sp=0xc820209f38
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820209f90 sp=0xc820209f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820209f98 sp=0xc820209f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, locked to thread]:
net._C2func_getaddrinfo(0xa00720, 0x0, 0xc8201f8030, 0xc8201fa000, 0x0, 0x0, 0x0)
	??:0 +0x4d
net.cgoLookupIPCNAME(0xc82006df40, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x545a00)
	/usr/local/go/src/net/cgo_unix.go:111 +0x1ac
net.cgoLookupIP(0xc82006df40, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3e6240)
	/usr/local/go/src/net/cgo_unix.go:163 +0x56
net.lookupIP(0xc82006df40, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup_unix.go:67 +0x94
net.glob.func15(0x545a50, 0xc82006df40, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/hook.go:10 +0x4d
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:106 +0x71
internal/singleflight.(*Group).doCall(0x6b23e0, 0xc8200102d0, 0xc82006df40, 0xa, 0xc820012300)
	/usr/local/go/src/internal/singleflight/singleflight.go:93 +0x2c
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:86 +0x3ed
error: external filter 'git-lfs smudge %f' failed 2
error: external filter 'git-lfs smudge %f' failed
fatal: dist/OmicsIntegrator-0.3.1.tar.gz: smudge filter lfs failed
```

Has anyone tried to do this lately? Is something awry with our git-lfs config?

**Comment by agitter** [comment]
I just tried a fresh clone of the repository and it worked for me (details below).  I'm running git bash on Windows 10 with the following versions of git and git-lfs
```
$ git-lfs env
git-lfs/1.4.1 (GitHub; windows amd64; go 1.7; git 2070e4c)
git version 2.9.2.windows.1
```

The `git clone` on our last [Travis build](https://travis-ci.org/fraenkel-lab/OmicsIntegrator/builds/349516618#L421) also worked using git version 2.15.1 and go version 1.8.3.

My clone output
```
$ git clone https://github.com/fraenkel-lab/OmicsIntegrator.git
Cloning into 'OmicsIntegrator'...
remote: Enumerating objects: 2472, done.
remote: Total 2472 (delta 0), reused 0 (delta 0), pack-reused 2472
Receiving objects: 100% (2472/2472), 258.45 MiB | 2.17 MiB/s, done.
Resolving deltas: 100% (870/870), done.
Checking connectivity... done.
Downloading dist/OmicsIntegrator-0.3.1.tar.gz (562.57 MB)
Downloading dist/OmicsIntegrator-Examples.tar.gz (196.63 MB)
Downloading example/dnaseClus/wgEncodeRegDnaseClusteredV2.fasta.gz (138.61 MB)
```

Based on your stack trace, could it be related to your version of go?

**Comment by sgosline** [comment]
Ok, I'm not sure what the issue was but I reinstalled `git`, `git-lfs`, and `go` from `homebrew` and it seems to have done the trick. I was mainly concerned it was something about Europe and the GDPR that was blocking me ;).
